spring:
  kafka:
    #kafka地址
    bootstrap-servers:
      - http://localhost:9092
    #生产者的配置
    producer:
      #key序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #每批次发送消息的数量
      batch-size: 16
      #发送失败重试次数
      retries: 0
      #即32MB的批处理缓冲区
      buffer-memory: 33554432
    #消费者的配置
    consumer:
      #key的解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #是否开启自动提交
      enable-auto-commit: true
      #自动提交的时间间隔
      auto-commit-interval: 100
      #在kafka/config文件的consumer.properties中有配置
      group-id: test-consumer-group
